version: "3.9"

services:
  backend:
    build: ./flask_app
    container_name: flask-finance-backend
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    container_name: flask-finance-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
