services:

  db:
    container_name: mysql-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"

  backend-adonis:
    build: ./backend
    container_name: backend-adonis
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - CI=true
      - NODE_ENV=development
      - TZ=UTC
      - PORT=3333
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=dGhpcyBpcyBhIDMyIGNoYXJhY3RlciBzdHJpbmdfXzEyMzQ1Njc4OTA=
      - SESSION_DRIVER=cookie
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=app
    depends_on:
      - db

  backend-flask:
    build: ./simulator
    container_name: backend-flask
    ports:
      - "5000:5000"
    volumes:
      - ./simulator:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    container_name: frontend-vite-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CI=true
      - VITE_FRONTEND_URL=http://localhost:5173
      - VITE_BACKEND_URL=http://localhost:3333
      - VITE_SIMULATOR_URL=http://localhost:5000
    depends_on:
      - backend-adonis
      - backend-flask