services:

  db:
    container_name: mysql-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  backend-flask:
    build: ./simulator
    container_name: backend-flask
    ports:
      - "5000:5000"
    volumes:
      - ./simulator:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    container_name: frontend-vite-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-flask